version: "3.9"

services:
  api:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
    image: feed-me-app:latest

  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
