version: 2.1

orbs:
  elixir: coletiv/elixir@0.1.2

jobs:
  build-and-test:
    docker:
      - image: circleci/elixir:1.10.4
    steps:
      - checkout
      - elixir/build
      - check-format
      - run:
          command: mix credo --strict
          name: Static analysis to Elixir source code
      - run:
          command: mix test
          name: Execute tests

workflows:
  build-and-test:
    jobs:
      - build-and-test
