version: 2.1

orbs:
  elixir: coletiv/elixir@0.1.2

jobs:
  build-and-test:
    parameters:
      elixir-version:
        type: string
    docker:
      - image: circleci/elixir:<< parameters.elixir-version >>
    steps:
      - checkout
      - elixir/build
      - elixir/check-format
      - run:
          command: mix credo --strict
          name: Static analysis to Elixir source code
      - run:
          command: mix test
          name: Execute tests

workflows:
  build-and-test:
    jobs:
      - build-and-test:
          matrix:
            parameters:
              elixir-version: ["1.10.4"]
