version: 2.1

orbs:
  elixir: coletiv/elixir@0.1.2

jobs:
  build-and-test:
    parameters:
      elixir-version:
        type: string
    docker:
      - image: circleci/elixir:<< parameters.elixir-version >>
      - image: circleci/postgres:12-alpine
    steps:
      - checkout
      - elixir/build
      - elixir/check-format
      - run:
          name: Static analysis to Elixir source code
          command: mix credo --strict --ignore tagtodo
      - elixir/test
  deploy:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run:
          name: Deploy `master` to Gigalixir
          command: git push gigalixir master

workflows:
  build-test-deploy:
    jobs:
      - build-and-test:
          matrix:
            parameters:
              elixir-version: ["1.10.4"]
      - deploy:
          requires:
            - build-and-test
          # filters:
          #   branches:
          #     only:
          #       - master
